### ISSUE TITLE
Ldes members sync fail to client sink

### ISSUE THREAD

**Issue by zargha** [Informatievlaanderen/VSDS-LDESWorkbench-NiFi#43]
While testing out gipod e2e test https://github.com/Informatievlaanderen/VSDS-LDES-E2E-testing/blob/main/e2e-test/use-cases/gipod/3.synchronize-ldes/README.md, the ldes members cannot be synchronized to ldes client sink.

### Error log:
```
022-11-21 14:51:57,378 WARN [Timer-Driven Process Thread-3] org.apache.sis.system The “SIS_DATA” environment variable is not set.
2022-11-21 14:51:59,259 INFO [pool-7-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Initiating checkpoint of FlowFile Repository
2022-11-21 14:51:59,259 INFO [pool-7-thread-1] o.a.n.c.r.WriteAheadFlowFileRepository Successfully checkpointed FlowFile Repository with 0 records in 0 milliseconds
2022-11-21 14:52:04,423 ERROR [Timer-Driven Process Thread-3] org.apache.jena.riot There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
2022-11-21 14:52:04,427 ERROR [Timer-Driven Process Thread-3] b.v.i.ldes.processors.LdesClient LdesClient[id=99600790-ac5a-35f8-e4f6-7d6084b9207f] Processing halted: yielding [1 sec]
be.vlaanderen.informatievlaanderen.ldes.client.exceptions.UnparseableFragmentException: LdesClient cannot parse fragment id: http://ldes-server-simulator/api/v1/ldes/mobility-hindrances
        at be.vlaanderen.informatievlaanderen.ldes.client.services.LdesFragmentFetcherImpl.fetchFragment(LdesFragmentFetcherImpl.java:78)
        at be.vlaanderen.informatievlaanderen.ldes.client.services.LdesServiceImpl.processNextFragment(LdesServiceImpl.java:125)
        at be.vlaanderen.informatievlaanderen.ldes.processors.LdesClient.onTrigger(LdesClient.java:72)
        at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
        at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1356)
        at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:246)
        at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:102)
        at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.jena.riot.RiotException: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
        at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:156)
        at org.apache.jena.riot.lang.LangJSONLD11.handleJsonLdError(LangJSONLD11.java:80)
        at org.apache.jena.riot.lang.LangJSONLD11.read(LangJSONLD11.java:67)
        at org.apache.jena.riot.RDFParser.read(RDFParser.java:416)
        at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:406)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:356)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:259)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:271)
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:592)
        at be.vlaanderen.informatievlaanderen.ldes.client.services.LdesFragmentFetcherImpl.fetchFragment(LdesFragmentFetcherImpl.java:58)
        ... 13 common frames omitted
2022-11-21 14:52:04,431 WARN [Timer-Driven Process Thread-3] o.a.n.controller.tasks.ConnectableTask Processing halted: uncaught exception in Component [LdesClient[id=99600790-ac5a-35f8-e4f6-7d6084b9207f]]
be.vlaanderen.informatievlaanderen.ldes.client.exceptions.UnparseableFragmentException: LdesClient cannot parse fragment id: http://ldes-server-simulator/api/v1/ldes/mobility-hindrances
        at be.vlaanderen.informatievlaanderen.ldes.client.services.LdesFragmentFetcherImpl.fetchFragment(LdesFragmentFetcherImpl.java:78)
        at be.vlaanderen.informatievlaanderen.ldes.client.services.LdesServiceImpl.processNextFragment(LdesServiceImpl.java:125)
        at be.vlaanderen.informatievlaanderen.ldes.processors.LdesClient.onTrigger(LdesClient.java:72)
        at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
        at org.apache.nifi.controller.StandardProcessorNode.onTrigger(StandardProcessorNode.java:1356)
        at org.apache.nifi.controller.tasks.ConnectableTask.invoke(ConnectableTask.java:246)
        at org.apache.nifi.controller.scheduling.TimerDrivenSchedulingAgent$1.run(TimerDrivenSchedulingAgent.java:102)
        at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.jena.riot.RiotException: There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
        at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:156)
        at org.apache.jena.riot.lang.LangJSONLD11.handleJsonLdError(LangJSONLD11.java:80)
        at org.apache.jena.riot.lang.LangJSONLD11.read(LangJSONLD11.java:67)
        at org.apache.jena.riot.RDFParser.read(RDFParser.java:416)
        at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:406)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:356)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:259)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:271)
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:592)
        at be.vlaanderen.informatievlaanderen.ldes.client.services.LdesFragmentFetcherImpl.fetchFragment(LdesFragmentFetcherImpl.java:58)
        ... 13 common frames omitted
```

**Comment by zargha** [comment]
Issues has been solved in ldes-workbench-nifi tag: [20221109T103745](https://github.com/orgs/Informatievlaanderen/packages/container/ldes-workbench-nifi/49574120?tag=20221109T103745)
